### ISSUE TITLE
smoke & CO alarm

### ISSUE THREAD

**Issue by pribadihcr** [benjaminchodroff/alarmBeepDetect#1]
Hi @benjaminchodroff 

I need to classify temporal 3 (smoke alarm) and temporal 4 (CO alarm).
is using the code work ?

thanks

**Comment by benjaminchodroff** [comment]
Detecting T3 vs T4 would require some code changes, but could be done. 

This code detects beeps of a certain length and frequency. To detect T3 vs T4 would likely require two additional sliding windows. One window to detect how many beeps occurred within a certain duration (3 half-second beeps vs 4), and another window to ensure there was a "no beep" pause of a certain duration after hearing the required number of beeps (one and a half seconds). ISO 8201 does not specify what frequency - so this can be challenging, because loud music can lead to false positives.

Feel free to submit a pull request - sounds like a good project, but please understand this is just a demo shouldn't be used in any real safety system.
